name: API Deployment pipeline

on:
  push:
    paths:
      - "api/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to DigitalOcean
        run: |
          sshpass -p ${{ secrets.DEPLOY_PASSWORD }} ssh -o StrictHostKeyChecking=no root@143.110.249.97 <<EOF
          cd Nebula

      - name: Pull latest changes
        run: git pull

      - name: Install dependencies
        run: |
          cd api
          npm install
      - name: Build and restart server
        run: |
          npm run prod
          EOF
