name: API Deployment pipeline

on:
  push:
    paths:
      - "api/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 64.227.137.37 >> ~/.ssh/known_hosts

      - name: Pull latest changes
        run: |
          cd /root/Nebula
          git pull

      - name: Install dependencies
        run: |
          cd /root/Nebula/api
          npm install

      - name: Compile TypeScript
        run: tsc

      - name: Restart server
        run: |
          pm2 restart ./build/index.js
