name: API Deployment pipeline

on:
  push:
    paths:
      - "api/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 64.227.137.37 >> ~/.ssh/known_hosts

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest changes
        run: |
          ssh root@64.227.137.37 'cd /root/Nebula && git pull'

      - name: Install dependencies
        run: |
          ssh root@64.227.137.37 'cd /root/Nebula/api && npm install'

  build:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Compile TypeScript
        run: |
          ssh root@64.227.137.37 'cd /root/Nebula && tsc'

      - name: Restart server
        run: |
          ssh root@64.227.137.37 'pm2 restart ./build/index.js'
