name: API Deployment pipeline

on:
  push:
    paths:
      - "api/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: connect and auth to server
        run: |
          ssh root@64.227.137.37
          ${{ secrets.DEPLOY_PASSWORD }}

      - name: Pull latest changes
        run: |
          cd /root/Nebula
          git pull

      - name: Install dependencies
        run: |
          cd /root/Nebula/api
          npm install

      - name: compile ts
        run: tsc

      - name: restart server
        run: |
          pm2 restart ./build/index.js
          EOF
