name: API Deployment pipeline

on:
  push:
    paths:
      - "api/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to DigitalOcean
        run: |
          sshpass -p ${{ secrets.DEPLOY_PASSWORD }} ssh -o StrictHostKeyChecking=no root@143.110.249.97 <<EOF

      - name: Pull latest changes
        run: |
          git pull
          cd Nebula

      - name: Install dependencies
        run: |
          cd api
          npm install

      - name: compile ts
        run: tsc

      - name: restart server
        run: |
          pm2 restart ./build/index.js
          EOF
